### ISSUE TITLE
Room Managment Error/Exception Emails

### ISSUE THREAD

**Issue by cfdaltoncftn** [CentralAZ/Rock-CentralAZ#141]
### Description

Everytime we set up a Room management form in Rock, this email comes to us:

An exception has occurred. Details of this error can be found below:
An error occurred for Jasmine Meadows on the Rock RMS site on page: 
https://rock.cftn.com:443/ReservationDetail?ReservationId=7

NullReferenceException in Anonymously Hosted DynamicMethods Assembly

Message
Object reference not set to an instance of an object.

Stack Trace
at lambda_method(Closure , ReservationResourceSummary )
at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Rock.Web.UI.Controls.Grid.SetLinqDataSource[T](IQueryable`1 qry)
at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationDetail.BindReservationResourcesGrid()
at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationDetail.SaveReservationResource()
at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationDetail.dlgReservationResource_SaveClick(Object sender, EventArgs e)
at Rock.Web.UI.Controls.ModalDialog.SaveLink_ServerClick(Object sender, EventArgs e)
at System.Web.UI.HtmlControls.HtmlAnchor.OnServerClick(EventArgs e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Steps to Reproduce

1. Create new form.
2. Svae form.
3. Error email is triggered.

**Expected behavior:** 

No error.

**Actual behavior:** 

Error email is triggered.

### Versions

* **Rock Version:** Rock McKinley 9.4
* **Client Culture Setting:** en-us

**Comment by tcavaletto** [comment]
Are you still encountering the issue after updating to 1.5.2?
