### ISSUE TITLE
[RR] Since upgrading to version 1.5.3, receiving SQL Error "Invalid column name 'DefaultCleanupTime'"

### ISSUE THREAD

**Issue by brendan0820** [CentralAZ/Rock-CentralAZ#169]
Since we upgraded to version 1.5.3, we are no longer able to access the plugin.  When attempting to use the plugin we receive the following error: 

Invalid column name 'DefaultCleanupTime'.

-- SqlException in .Net SqlClient Data Provider

> Message
> Invalid column name 'DefaultCleanupTime'.
> Stack Trace
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at System.Data.SqlClient.SqlDataReader.get_MetaData()
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
>    at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
>    at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
>    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)

**Comment by tcavaletto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Since upgrading to version 1.5.3, receiving SQL Error "Invalid column name 'DefaultCleanupTime'](https://trello.com/c/gKhUeUr2/30-since-upgrading-to-version-153-receiving-sql-error-invalid-column-name-defaultcleanuptime)

**Comment by tcavaletto** [comment]
@brendan0820 What was the last Room Management migration run on your system?
