### ISSUE TITLE
RR - Can't Delete Workflow

### ISSUE THREAD

**Issue by jrockman13** [CentralAZ/Rock-CentralAZ#81]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Yesterday, I added another workflow to notify when reservations are changed. Today, I realized it was a bad idea and tried to delete it. I tried this on our sandbox and did NOT get the error, although  I created, saved, and deleted all within a couple minutes.

### Steps to Reproduce

1. Create new workflow (trigger - reservation updated, action Room Reservation Reminder Notification)
2. Save
3. Click X to delete
4. Click Save

**Expected behavior:** 

The workflow deletes.

**Actual behavior:** 

I get this message:

Error
The DELETE statement conflicted with the REFERENCE constraint "FK__com_centralaz_RoomManagement_ReservationWorkflow_ReservationWorkflowTriggerId". The conflict occurred in database "cbc-rock-db", table "dbo._com_centralaz_RoomManagement_ReservationWorkflow", column 'ReservationWorkflowTriggerId'. The statement has been terminated.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing)
   at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationConfiguration.btnSave_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Plugins\com_centralaz\RoomManagement\ReservationConfiguration.ascx.cs:line 198
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** "en-us"  <a href="https://www.rockrms.com/github-detect-client-culture-setting" target="_blank">unsure? detect what yours is here (right click and open in new window)</a>

**Comment by tcavaletto** [comment]
Fixed

**Comment by jrockman13** [comment]
Thanks! Question: What do I need to do to update? My rock install shows 1.2.2 installed.
