### ISSUE TITLE
Trying to reserve a room with an approval group tied to it causes an error in Rock V8

### ISSUE THREAD

**Issue by tcavaletto** [CentralAZ/Rock-CentralAZ#88]
Reported by David Spooner

Produces the following stack trace:
at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationDetail.b__46(GroupMember m) in c:\inetpub\wwwroot\Plugins\com_centralaz\RoomManagement\ReservationDetail.ascx.cs:line 1251
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.d__64`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationDetail.gLocations_RowDataBound(Object sender, GridViewRowEventArgs e) in c:\inetpub\wwwroot\Plugins\com_centralaz\RoomManagement\ReservationDetail.ascx.cs:line 1251
   at System.Web.UI.WebControls.GridView.OnRowDataBound(GridViewRowEventArgs e)
   at Rock.Web.UI.Controls.Grid.OnRowDataBound(GridViewRowEventArgs e)
   at System.Web.UI.WebControls.GridView.CreateRow(Int32 rowIndex, Int32 dataSourceIndex, DataControlRowType rowType, DataControlRowState rowState, Boolean dataBind, Object dataItem, DataControlField[] fields, TableRowCollection rows, PagedDataSource pagedDataSource)
   at System.Web.UI.WebControls.GridView.CreateChildControls(IEnumerable dataSource, Boolean dataBinding)
   at Rock.Web.UI.Controls.Grid.CreateChildControls(IEnumerable dataSource, Boolean dataBinding)
   at System.Web.UI.WebControls.CompositeDataBoundControl.PerformDataBinding(IEnumerable data)
   at System.Web.UI.WebControls.GridView.PerformDataBinding(IEnumerable data)
   at System.Web.UI.WebControls.DataBoundControl.OnDataSourceViewSelectCallback(IEnumerable data)
   at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationDetail.BindReservationLocationsGrid() in c:\inetpub\wwwroot\Plugins\com_centralaz\RoomManagement\ReservationDetail.ascx.cs:line 1165
   at RockWeb.Plugins.com_centralaz.RoomManagement.ReservationDetail.dlgReservationLocation_SaveClick(Object sender, EventArgs e) in c:\inetpub\wwwroot\Plugins\com_centralaz\RoomManagement\ReservationDetail.ascx.cs:line 1043
   at Rock.Web.UI.Controls.ModalDialog.SaveLink_ServerClick(Object sender, EventArgs e)
   at System.Web.UI.HtmlControls.HtmlAnchor.OnServerClick(EventArgs e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Included is a video of the error:
https://www.screencast.com/t/zWHXKGNVE38d

**Comment by tcavaletto** [comment]
Issue solved in v1.3
